name: wireguard-socks-proxy
services:
  wireguard-socks-proxy:
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
    container_name: wireguard-socks-proxy
    volumes:
      - /directory/containing/your/wireguard/conf/file/:/etc/wireguard/:ro
    ports:
      - 1080:1080
    image: wireguard-socks-proxy:latest
    platform: linux/arm64
    privileged: true # Allows sysctl modifications
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
