name: wireguard-socks-proxy
services:
  wireguard-socks-proxy:
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
    container_name: wireguard-socks-proxy
    volumes:
      - /directory/containing/your/wireguard/conf/file/:/etc/wireguard/:ro
    ports:
      - 1080:1080
    image: ghcr.io/chosomeister/docker-wireguard-socks-proxy:latest
    privileged: true
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
