name: Publish image to ghcr.io

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag"
        required: true
        default: "latest"

jobs:
  publish_image:
    runs-on: ubuntu-22.04

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GGHCR_TOKEN }}" | docker login ghcr.io -u chosomeister --password-stdin

      # Extract the version from the workflow inputs
      - name: Extract version
        id: get_version
        run: echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV

      # Build and push the multi-platform Docker image
      - name: Build and push multi-platform Docker image
        run: |
          docker buildx create --use
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/chosomeister/docker-wireguard-socks-proxy:${{ env.VERSION }} \
            --tag ghcr.io/chosomeister/docker-wireguard-socks-proxy:latest \
            --push .

      # Create a GitHub Release
      - name: Create GitHub Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GGHCR_TOKEN }}
        run: |
          gh release create v${{ env.VERSION }} --title "Release v${{ env.VERSION }}" --notes "Release notes for version ${{ env.VERSION }}"
